import '@/styles/reset.css'
import { ReduxProvider } from '@/store/provider'

export const metadata = {
	title: 'Furniture store',
	description: 'Generated by create next app',
}

export default function ChckoutLayout({ children }) {
	return <>{children}</>
}
