import '@/styles/reset.css'
import { ReduxProvider } from '@/store/provider'

export const metadata = {
	title: 'Furniture store',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className='antialiased'>{children}</body>
		</html>
	)
}
