import '@/styles/reset.css'
import React from 'react'

export const metadata = {
	title: 'Furniture store',
	description: 'Generated by create next app',
}

interface ICheckoutLayoutProp {
	children: React.ReactNode
}

export default function CheckoutLayout({ children }: ICheckoutLayoutProp) {
	return <>{children}</>
}
