import '@/styles/reset.css'
import type React from 'react'

export const metadata = {
	title: 'Furniture store',
	description: 'Generated by create next app',
}

type TAuthLayoutProps = {
	children: React.ReactNode
}

export default function AuthLayout({ children }: TAuthLayoutProps) {
	return <>{children}</>
}
