import '@/styles/reset.css'
import { ReduxProvider } from '@/store/provider'
import type React from 'react'

export const metadata = {
	title: 'Furniture store',
	description: 'Generated by create next app',
}
interface IContactLayoutProps {
	children: React.ReactNode
}

export default function ContactLayout({ children }: IContactLayoutProps) {
	return <ReduxProvider>{children}</ReduxProvider>
}
