import '@/styles/reset.css'
import { Provider } from 'react-redux'
import store from '@/store/store'
import { ReduxProvider } from '@/store/provider'

export const metadata = {
	title: 'Furniture store',
	description: 'Generated by create next app',
}

export default function ContactLayout({ children }) {
	return <ReduxProvider>{children}</ReduxProvider>
}
