import '@/styles/reset.css'
import type React from 'react'

export const metadata = {
	title: 'Furniture store',
	description: 'Generated by create next app',
}

export default function CartLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return <>{children}</>
}
