import '@/styles/reset.css'

export const metadata = {
	title: 'Furniture store',
	description: 'Generated by create next app',
}

export default function CartLayout({ children }) {
	return <>{children}</>
}
