import '@/styles/reset.css'

import type React from 'react'

export const metadata = {
	title: 'Furniture store',
	description: 'Generated by create next app',
}
type TProfileLayout = {
	children: React.ReactNode
}

export default function ProfileLayout({ children }: TProfileLayout) {
	return <>{children}</>
}
